name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        c_compiler: [gcc, clang, cl]
        build_type: [Debug, Release]
        cxx_standard: ["20"]
        include:
          - c_compiler: gcc
            cxx_compiler: g++
          - c_compiler: clang
            cxx_compiler: clang++
          - c_compiler: cl
            cxx_compiler: cl
          - os: windows-latest
            test_name: .\Bin\UnitTest.exe
          - os: ubuntu-latest
            test_name: ./Bin/UnitTest
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    name: ${{ matrix.c_compiler }} - ${{ matrix.build_type }} - ${{ matrix.os }} - c++${{ matrix.cxx_standard }}
        
    runs-on: ${{matrix.os}}
    
    steps:
    - uses: actions/checkout@v3
    - uses: seanmiddleditch/gha-setup-ninja@v3
    - uses: seanmiddleditch/gha-setup-vsdevenv@master

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      env:
        CC: ${{matrix.c_compiler}}
        CXX: ${{matrix.cxx_compiler}}
      run: cmake ${{runner.workspace}} -G Ninja -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_STANDARD=${{ matrix.cxx_standard }}

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config ${{matrix.build_type}}
