name: Clang-Format
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Verify formatting
        run: |
          python ./support/run-clang-format.py -r src